// <auto-generated />
namespace mesh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20211208 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20211208));
        
        string IMigrationMetadata.Id
        {
            get { return "202112080622433_20211208"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
